export const moviesActionTypes = {
	GET_ALL_MOVIES_REQUEST: 'GET_ALL_MOVIES_REQUEST',
	GET_ALL_MOVIES_REQUEST_SUCCESS: 'GET_ALL_MOVIES_REQUEST_SUCCESS',
    GET_ALL_MOVIES_REQUEST_FAILURE: 'GET_ALL_MOVIES_REQUEST_FAILURE'
};

export default moviesActionTypes;