export const moviesActionTypes = {
	GET_ALL_MOVIES_REQUEST: 'GET_ALL_MOVIES_REQUEST',
	GET_ALL_MOVIES_REQUEST_SUCCESS: 'GET_ALL_MOVIES_SUCCESS',
	GET_ALL_MOVIES_REQUEST_FAILURE: 'GET_ALL_MOVIES_FAILURE',
	
	GET_MOVIE_DETAILS_REQUEST: 'GET_MOVIE_DETAILS_REQUEST',
	GET_MOVIE_DETAILS_REQUEST_SUCCESS: 'GET_MOVIE_DETAILS_SUCCESS',
	GET_MOVIE_DETAILS_REQUEST_FAILURE: 'GET_MOVIE_DETAILS_FAILURE',
};

export default moviesActionTypes;